### ISSUE TITLE
App needs lifespan in uvicorn-bare

### ISSUE THREAD

**Issue by garvenlee** [nDmitry/web-banchmarks#28]
Current Python code shows that the db instance is initialized after concurrent requests come in, while golang code initiates db before listening. 

And when the first batch of requests come in, app in the uvicorn-bare may concurrently connect the postgres, which may cause some performance issues in db.

**Comment by nDmitry** [comment]
Thanks, will look into it again. Also it is time to update the dependencies. The idea was to create a pool of connections early and than acquire ready connections from the pool (golang and nodejs do the same). Seems like I did exactly that in all Python implementations except for uvicorn, where the pool is created upon the first request and then reused (for some reason I don't remember).

**Comment by garvenlee** [comment]
> the pool is created upon the first request

But uvicorn is asynchronous, and if the db initialization is placed in the `__call__`, `asyncio.Lock` is required when requests come in, which can prevent concurrent creation of connection pool. But it’s better to create the pool before ASGI App is ready, just like golang and nodejs do.
